// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1vAFqyoza-AM53TG5DSb39UaCeUY4fr4',
    appId: '1:696604779246:web:af0cefe6c05e6428fa09ff',
    messagingSenderId: '696604779246',
    projectId: 'aihairapp-b44e7',
    authDomain: 'aihairapp-b44e7.firebaseapp.com',
    storageBucket: 'aihairapp-b44e7.firebasestorage.app',
    measurementId: 'G-3L2HCXJMYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2hTwIcWI2UaxFvbOVvWVlSCpsld04Ff8',
    appId: '1:696604779246:android:5c85e3e75608a410fa09ff',
    messagingSenderId: '696604779246',
    projectId: 'aihairapp-b44e7',
    storageBucket: 'aihairapp-b44e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfmx8Moc_fCnHS5Yy4SCJLGrWC1s7NMXM',
    appId: '1:696604779246:ios:4088be123200cd2ffa09ff',
    messagingSenderId: '696604779246',
    projectId: 'aihairapp-b44e7',
    storageBucket: 'aihairapp-b44e7.firebasestorage.app',
    iosBundleId: 'com.al.hair.app.alHairApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfmx8Moc_fCnHS5Yy4SCJLGrWC1s7NMXM',
    appId: '1:696604779246:ios:4088be123200cd2ffa09ff',
    messagingSenderId: '696604779246',
    projectId: 'aihairapp-b44e7',
    storageBucket: 'aihairapp-b44e7.firebasestorage.app',
    iosBundleId: 'com.al.hair.app.alHairApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1vAFqyoza-AM53TG5DSb39UaCeUY4fr4',
    appId: '1:696604779246:web:711f25b3d4deb0aafa09ff',
    messagingSenderId: '696604779246',
    projectId: 'aihairapp-b44e7',
    authDomain: 'aihairapp-b44e7.firebaseapp.com',
    storageBucket: 'aihairapp-b44e7.firebasestorage.app',
    measurementId: 'G-6QCD0VNZ28',
  );
}
